site_name: Articulate
pages:
  - Introduction: index.md
  - Guides:
    - Setup: guides/setup.md
    - Getting Started: guides/getting-started.md
  - Entities:
    - Introduction: entities/index.md
    - Attributes: entities/attributes.md
    - State: entities/state.md
    - Multiple Inheritance: entities/inheritance.md
    - Mappers: entities/mappers.md
    - Mappings: entities/mappings.md
    - Repositories: entities/repositories.md
  - Attributes:
    - Introduction: attributes/index.md
    - Components: attributes/components.md
  - Sources:
    - Introduction: sources/index.md
    - Illuminate: sources/illuminate.md
    - Respite: sources/respite.md
theme: readthedocs
